export const AUTOMATION_DRAFT_INTERVAL_MS = 7 * 24 * 60 * 60 * 1000;

export interface AutomationDefinitionSchedule {
  id: string;
  enabled: boolean;
  lastDraftAt?: number;
  name: string;
  sourcePattern: string;
  sourceSuggestionId: string;
  projectId?: string;
}

export function isAutomationDraftDue(
  definition: Pick<AutomationDefinitionSchedule, "enabled" | "lastDraftAt">,
  now: number
): boolean {
  return definition.enabled && (!definition.lastDraftAt || now - definition.lastDraftAt >= AUTOMATION_DRAFT_INTERVAL_MS);
}

export function buildAutomationDraft(definition: AutomationDefinitionSchedule, now: number) {
  const workflowMatch = definition.sourcePattern.match(/^Workflow:\s*(.+)$/);
  const cadenceKey = Math.floor(now / AUTOMATION_DRAFT_INTERVAL_MS);
  return {
    projectId: definition.projectId,
    idempotencyKey: `automation-definition:${definition.id}:${cadenceKey}`,
    kind: "AUTOMATION" as const,
    title: `Review automation scope: ${definition.name}`,
    desiredOutcome: `Review the proposed automation for ${definition.sourcePattern} and explicitly approve or reject dispatch.`,
    context: "Generated by an active automation definition. This review gate cannot be auto-dispatched.",
    workflowId: workflowMatch?.[1]?.trim(),
    priority: 3 as const,
    riskLevel: "MEDIUM" as const,
    isMutating: false,
    requestedBy: "automation-definition-scheduler",
    requiredApprovals: ["operator"],
    // The normal Work Order governance flow treats an operator approval as a
    // pending gate. Set that persisted state directly instead of relying on a
    // later governance refresh to promote a nominal DRAFT.
    state: "AWAITING_APPROVAL" as const,
    requiredHumanAction: "Review scope, verification plan, and dispatch decision.",
    acceptanceCriteria: [
      {
        id: "operator-scope-review",
        title: "Operator confirms bounded scope",
        description: "Confirm the automation remains non-mutating until a separate dispatch approval.",
        verificationMethod: "MANUAL" as const,
        status: "PENDING" as const,
      },
      {
        id: "verification-receipt-plan",
        title: "Verification receipt plan is defined",
        description: "Confirm the run will produce a reviewable verification receipt.",
        verificationMethod: "CHECKLIST" as const,
        status: "PENDING" as const,
      },
    ],
    metadata: { automationDefinitionId: definition.id, sourceSuggestionId: definition.sourceSuggestionId },
  };
}
